# type: ignore
"""add email notifications table

Revision ID: 5a7e6f8a2f9c
Revises: 
Create Date: 2026-06-22 20:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5a7e6f8a2f9c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(  # type: ignore
        'email_notifications',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('notification_type', sa.String(), nullable=False),
        sa.Column('recipient_email', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=False, server_default='RESEND'),
        sa.Column('provider_message_id', sa.String(), nullable=True),
        sa.Column('status', sa.String(), nullable=False, server_default='PENDING'),
        sa.Column('error_message', sa.String(), nullable=True),
        sa.Column('context_metadata', sa.JSON(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_email_notifications_user_id', 'email_notifications', ['user_id'], unique=False)
    op.create_index('idx_email_notifications_type', 'email_notifications', ['notification_type'], unique=False)
    op.create_index('idx_email_notifications_status', 'email_notifications', ['status'], unique=False)
    op.create_index('idx_email_notifications_created_at', 'email_notifications', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_email_notifications_created_at', table_name='email_notifications')
    op.drop_index('idx_email_notifications_status', table_name='email_notifications')
    op.drop_index('idx_email_notifications_type', table_name='email_notifications')
    op.drop_index('idx_email_notifications_user_id', table_name='email_notifications')
    op.drop_table('email_notifications')
    # ### end Alembic commands ###
